language: node_js
before_script:
  - openssl req -newkey rsa:2048 -nodes -keyout test.key -x509 -days 365 -out test.crt -subj /CN=localhost/C=fr/ST=rhone/L=lyon/O=atlantis-software/OU=synapps/emailAddress=test@localhost
node_js:
  - '6'
  - '8'
  - '9'
sudo: false
after_success: npm run coveralls
